# Generated by Django 4.0.5 on 2022-06-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_actor_date_of_birth_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.IntegerField(default=0),
        ),
    ]
